      - name: Enviar para o GitHub do cliente
        env:
          TOKEN: ${{ secrets.CLIENT_PUSH_TOKEN }}
        run: |
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"

          git remote remove cliente 2>/dev/null || true
          git remote add cliente https://x-access-token:${TOKEN}@github.com/wesley-gois2/site-empresa-x.git
          git push cliente HEAD:main --force
