name: Enviar para repo do cliente

on:
  push:
    branches:
      - main

jobs:
  enviar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o cÃ³digo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enviar para o GitHub da Organization
        env:
          TOKEN: ${{ secrets.CLIENT_PUSH_TOKEN }}
        run: |
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"

          git remote remove cliente 2>/dev/null || true
          git remote add cliente https://x-access-token:${TOKEN}@github.com/statuscompany-clients/site-empresa-x.git
          git push cliente HEAD:main --force
